package Football.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Coach_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Field_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Match_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Player_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Team_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c264298L), MetaIdFactory.conceptId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c2e0dd5L), MetaIdFactory.conceptId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c220732L), MetaIdFactory.conceptId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667aL), MetaIdFactory.conceptId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667bL)).seal();
}
