package Football.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Positions extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Positions() {
    super(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c23d431L, "Positions", "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384369");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Goalkeeper_0 = new EnumerationDescriptor.MemberDescriptor("Goalkeeper", "Goalkeeper", 0x37f2b1723c23d432L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384370");
  private final EnumerationDescriptor.MemberDescriptor myMember_RightBack_0 = new EnumerationDescriptor.MemberDescriptor("RightBack", "RB", 0x37f2b1723c23d437L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384375");
  private final EnumerationDescriptor.MemberDescriptor myMember_RightWingBack_0 = new EnumerationDescriptor.MemberDescriptor("RightWingBack", "RWB", 0x37f2b1723c23d43dL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384381");
  private final EnumerationDescriptor.MemberDescriptor myMember_LeftBack_0 = new EnumerationDescriptor.MemberDescriptor("LeftBack", "LB", 0x37f2b1723c23d441L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384385");
  private final EnumerationDescriptor.MemberDescriptor myMember_LeftWingBack_0 = new EnumerationDescriptor.MemberDescriptor("LeftWingBack", "LWB", 0x37f2b1723c23d446L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384390");
  private final EnumerationDescriptor.MemberDescriptor myMember_Sweeper_0 = new EnumerationDescriptor.MemberDescriptor("Sweeper", "SW", 0x37f2b1723c23d44cL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384396");
  private final EnumerationDescriptor.MemberDescriptor myMember_CenterBack_0 = new EnumerationDescriptor.MemberDescriptor("CenterBack", "CB", 0x37f2b1723c23d461L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384417");
  private final EnumerationDescriptor.MemberDescriptor myMember_CentralDefensiveMidfield_0 = new EnumerationDescriptor.MemberDescriptor("CentralDefensiveMidfield", "CDM", 0x37f2b1723c23d469L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384425");
  private final EnumerationDescriptor.MemberDescriptor myMember_CentralMidfield_0 = new EnumerationDescriptor.MemberDescriptor("CentralMidfield", "CM", 0x37f2b1723c23d472L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384434");
  private final EnumerationDescriptor.MemberDescriptor myMember_CentralAttackingMidfield_0 = new EnumerationDescriptor.MemberDescriptor("CentralAttackingMidfield", "CAM", 0x37f2b1723c23d47cL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384444");
  private final EnumerationDescriptor.MemberDescriptor myMember_RightMidfield_0 = new EnumerationDescriptor.MemberDescriptor("RightMidfield", "RM", 0x37f2b1723c23d487L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384455");
  private final EnumerationDescriptor.MemberDescriptor myMember_RightWing_0 = new EnumerationDescriptor.MemberDescriptor("RightWing", "RW", 0x37f2b1723c23d493L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384467");
  private final EnumerationDescriptor.MemberDescriptor myMember_SecondStriker_0 = new EnumerationDescriptor.MemberDescriptor("SecondStriker", "SS", 0x37f2b1723c23d4a0L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384480");
  private final EnumerationDescriptor.MemberDescriptor myMember_CentreForward_0 = new EnumerationDescriptor.MemberDescriptor("CentreForward", "CF", 0x37f2b1723c23d4aeL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384494");
  private final EnumerationDescriptor.MemberDescriptor myMember_Striker_0 = new EnumerationDescriptor.MemberDescriptor("Striker", "ST", 0x37f2b1723c23d4bdL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384509");
  private final EnumerationDescriptor.MemberDescriptor myMember_LeftMidfield_0 = new EnumerationDescriptor.MemberDescriptor("LeftMidfield", "LM", 0x37f2b1723c23d4cdL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384525");
  private final EnumerationDescriptor.MemberDescriptor myMember_LeftWing_0 = new EnumerationDescriptor.MemberDescriptor("LeftWing", "LW", 0x37f2b1723c23d4deL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643384542");
  private final EnumerationDescriptor.MemberDescriptor myMember_Defense_0 = new EnumerationDescriptor.MemberDescriptor("Defense", "Defense", 0x37f2b1723c25e9f2L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643521010");
  private final EnumerationDescriptor.MemberDescriptor myMember_Midfield_0 = new EnumerationDescriptor.MemberDescriptor("Midfield", "Midfield", 0x37f2b1723c25ea05L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643521029");
  private final EnumerationDescriptor.MemberDescriptor myMember_Forward_0 = new EnumerationDescriptor.MemberDescriptor("Forward", "Forward", 0x37f2b1723c25ea19L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643521049");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c23d431L, 0x37f2b1723c23d432L, 0x37f2b1723c23d437L, 0x37f2b1723c23d43dL, 0x37f2b1723c23d441L, 0x37f2b1723c23d446L, 0x37f2b1723c23d44cL, 0x37f2b1723c23d461L, 0x37f2b1723c23d469L, 0x37f2b1723c23d472L, 0x37f2b1723c23d47cL, 0x37f2b1723c23d487L, 0x37f2b1723c23d493L, 0x37f2b1723c23d4a0L, 0x37f2b1723c23d4aeL, 0x37f2b1723c23d4bdL, 0x37f2b1723c23d4cdL, 0x37f2b1723c23d4deL, 0x37f2b1723c25e9f2L, 0x37f2b1723c25ea05L, 0x37f2b1723c25ea19L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Goalkeeper_0, myMember_RightBack_0, myMember_RightWingBack_0, myMember_LeftBack_0, myMember_LeftWingBack_0, myMember_Sweeper_0, myMember_CenterBack_0, myMember_CentralDefensiveMidfield_0, myMember_CentralMidfield_0, myMember_CentralAttackingMidfield_0, myMember_RightMidfield_0, myMember_RightWing_0, myMember_SecondStriker_0, myMember_CentreForward_0, myMember_Striker_0, myMember_LeftMidfield_0, myMember_LeftWing_0, myMember_Defense_0, myMember_Midfield_0, myMember_Forward_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Goalkeeper":
        return myMember_Goalkeeper_0;
      case "RightBack":
        return myMember_RightBack_0;
      case "RightWingBack":
        return myMember_RightWingBack_0;
      case "LeftBack":
        return myMember_LeftBack_0;
      case "LeftWingBack":
        return myMember_LeftWingBack_0;
      case "Sweeper":
        return myMember_Sweeper_0;
      case "CenterBack":
        return myMember_CenterBack_0;
      case "CentralDefensiveMidfield":
        return myMember_CentralDefensiveMidfield_0;
      case "CentralMidfield":
        return myMember_CentralMidfield_0;
      case "CentralAttackingMidfield":
        return myMember_CentralAttackingMidfield_0;
      case "RightMidfield":
        return myMember_RightMidfield_0;
      case "RightWing":
        return myMember_RightWing_0;
      case "SecondStriker":
        return myMember_SecondStriker_0;
      case "CentreForward":
        return myMember_CentreForward_0;
      case "Striker":
        return myMember_Striker_0;
      case "LeftMidfield":
        return myMember_LeftMidfield_0;
      case "LeftWing":
        return myMember_LeftWing_0;
      case "Defense":
        return myMember_Defense_0;
      case "Midfield":
        return myMember_Midfield_0;
      case "Forward":
        return myMember_Forward_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
