package Football.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FieldType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FieldType() {
    super(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22666fL, "FieldType", "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290735");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ArtificialGrass_0 = new EnumerationDescriptor.MemberDescriptor("ArtificialGrass", "Artificial turf / synthetic grass", 0x37f2b1723c226670L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290736");
  private final EnumerationDescriptor.MemberDescriptor myMember_NaturalGrass_0 = new EnumerationDescriptor.MemberDescriptor("NaturalGrass", "Natural grass", 0x37f2b1723c226672L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290738");
  private final EnumerationDescriptor.MemberDescriptor myMember_Hybrid_0 = new EnumerationDescriptor.MemberDescriptor("Hybrid", "Hybrid turf", 0x37f2b1723c226675L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290741");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22666fL, 0x37f2b1723c226670L, 0x37f2b1723c226672L, 0x37f2b1723c226675L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ArtificialGrass_0, myMember_NaturalGrass_0, myMember_Hybrid_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_ArtificialGrass_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ArtificialGrass":
        return myMember_ArtificialGrass_0;
      case "NaturalGrass":
        return myMember_NaturalGrass_0;
      case "Hybrid":
        return myMember_Hybrid_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
