package Football.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Formations extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Formations() {
    super(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c4a2b8fL, "Formations", "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897103");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_FourThreeThree_0 = new EnumerationDescriptor.MemberDescriptor("FourThreeThree", "4-3-3", 0x37f2b1723c4a2b90L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897104");
  private final EnumerationDescriptor.MemberDescriptor myMember_ThreeFiveTwo_0 = new EnumerationDescriptor.MemberDescriptor("ThreeFiveTwo", "3-5-2", 0x37f2b1723c4a2b97L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897111");
  private final EnumerationDescriptor.MemberDescriptor myMember_FourTwoThreeOne_0 = new EnumerationDescriptor.MemberDescriptor("FourTwoThreeOne", "4-2-3-1", 0x37f2b1723c4a2b92L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897106");
  private final EnumerationDescriptor.MemberDescriptor myMember_FourFourTwo_0 = new EnumerationDescriptor.MemberDescriptor("FourFourTwo", "4-4-2", 0x37f2b1723c4a2b9cL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897116");
  private final EnumerationDescriptor.MemberDescriptor myMember_FourThreeTwoOne_0 = new EnumerationDescriptor.MemberDescriptor("FourThreeTwoOne", "4-3-2-1", 0x37f2b1723c4a2ba2L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897122");
  private final EnumerationDescriptor.MemberDescriptor myMember_FourFiveOne_0 = new EnumerationDescriptor.MemberDescriptor("FourFiveOne", "4-5-1", 0x37f2b1723c4a2ba8L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897128");
  private final EnumerationDescriptor.MemberDescriptor myMember_ThreeFourThree_0 = new EnumerationDescriptor.MemberDescriptor("ThreeFourThree", "3-4-3", 0x37f2b1723c4a2bafL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897135");
  private final EnumerationDescriptor.MemberDescriptor myMember_FourOneThreeTwo_0 = new EnumerationDescriptor.MemberDescriptor("FourOneThreeTwo", "4-1-3-2", 0x37f2b1723c4a2bb7L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897143");
  private final EnumerationDescriptor.MemberDescriptor myMember_FourOneTwoOneTwo_0 = new EnumerationDescriptor.MemberDescriptor("FourOneTwoOneTwo", "4-1-2-1-2", 0x37f2b1723c4a2bc0L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720645897152");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c4a2b8fL, 0x37f2b1723c4a2b90L, 0x37f2b1723c4a2b97L, 0x37f2b1723c4a2b92L, 0x37f2b1723c4a2b9cL, 0x37f2b1723c4a2ba2L, 0x37f2b1723c4a2ba8L, 0x37f2b1723c4a2bafL, 0x37f2b1723c4a2bb7L, 0x37f2b1723c4a2bc0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_FourThreeThree_0, myMember_ThreeFiveTwo_0, myMember_FourTwoThreeOne_0, myMember_FourFourTwo_0, myMember_FourThreeTwoOne_0, myMember_FourFiveOne_0, myMember_ThreeFourThree_0, myMember_FourOneThreeTwo_0, myMember_FourOneTwoOneTwo_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_FourThreeThree_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "FourThreeThree":
        return myMember_FourThreeThree_0;
      case "ThreeFiveTwo":
        return myMember_ThreeFiveTwo_0;
      case "FourTwoThreeOne":
        return myMember_FourTwoThreeOne_0;
      case "FourFourTwo":
        return myMember_FourFourTwo_0;
      case "FourThreeTwoOne":
        return myMember_FourThreeTwoOne_0;
      case "FourFiveOne":
        return myMember_FourFiveOne_0;
      case "ThreeFourThree":
        return myMember_ThreeFourThree_0;
      case "FourOneThreeTwo":
        return myMember_FourOneThreeTwo_0;
      case "FourOneTwoOneTwo":
        return myMember_FourOneTwoOneTwo_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
