package Football.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FieldSize extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FieldSize() {
    super(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22664dL, "FieldSize", "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290701");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Eleven_0 = new EnumerationDescriptor.MemberDescriptor("Eleven", "11v11", 0x37f2b1723c22664eL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290702");
  private final EnumerationDescriptor.MemberDescriptor myMember_Nine_0 = new EnumerationDescriptor.MemberDescriptor("Nine", "9v9", 0x37f2b1723c226653L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290707");
  private final EnumerationDescriptor.MemberDescriptor myMember_Seven_0 = new EnumerationDescriptor.MemberDescriptor("Seven", "7v7", 0x37f2b1723c59613bL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720646893883");
  private final EnumerationDescriptor.MemberDescriptor myMember_Five_0 = new EnumerationDescriptor.MemberDescriptor("Five", "5v5", 0x37f2b1723c226657L, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290711");
  private final EnumerationDescriptor.MemberDescriptor myMember_Three_0 = new EnumerationDescriptor.MemberDescriptor("Three", "3v3", 0x37f2b1723c22665bL, "r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290715");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22664dL, 0x37f2b1723c22664eL, 0x37f2b1723c226653L, 0x37f2b1723c59613bL, 0x37f2b1723c226657L, 0x37f2b1723c22665bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Eleven_0, myMember_Nine_0, myMember_Seven_0, myMember_Five_0, myMember_Three_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Eleven_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Eleven":
        return myMember_Eleven_0;
      case "Nine":
        return myMember_Nine_0;
      case "Seven":
        return myMember_Seven_0;
      case "Five":
        return myMember_Five_0;
      case "Three":
        return myMember_Three_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
