package Football.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBadge = createDescriptorForBadge();
  /*package*/ final ConceptDescriptor myConceptCoach = createDescriptorForCoach();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptLineup = createDescriptorForLineup();
  /*package*/ final ConceptDescriptor myConceptMatch = createDescriptorForMatch();
  /*package*/ final ConceptDescriptor myConceptPlayer = createDescriptorForPlayer();
  /*package*/ final ConceptDescriptor myConceptTeam = createDescriptorForTeam();
  /*package*/ final EnumerationDescriptor myEnumerationFieldSize = new EnumerationDescriptor_FieldSize();
  /*package*/ final EnumerationDescriptor myEnumerationFieldType = new EnumerationDescriptor_FieldType();
  /*package*/ final EnumerationDescriptor myEnumerationFormations = new EnumerationDescriptor_Formations();
  /*package*/ final EnumerationDescriptor myEnumerationPositions = new EnumerationDescriptor_Positions();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBadge, myConceptCoach, myConceptField, myConceptLineup, myConceptMatch, myConceptPlayer, myConceptTeam);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Badge:
        return myConceptBadge;
      case LanguageConceptSwitch.Coach:
        return myConceptCoach;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.Lineup:
        return myConceptLineup;
      case LanguageConceptSwitch.Match:
        return myConceptMatch;
      case LanguageConceptSwitch.Player:
        return myConceptPlayer;
      case LanguageConceptSwitch.Team:
        return myConceptTeam;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationFieldSize, myEnumerationFieldType, myEnumerationFormations, myEnumerationPositions);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBadge() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Badge", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c226f92L);
    b.class_(false, false, false);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643293074");
    b.version(3);
    b.property("id", 0x37f2b1723c23d414L).type(PrimitiveTypeId.INTEGER).origin("4031479720643384340").done();
    b.property("image", 0x37f2b1723c23d417L).type(PrimitiveTypeId.STRING).origin("4031479720643384343").done();
    b.property("colors", 0x37f2b1723c23d41aL).type(PrimitiveTypeId.STRING).origin("4031479720643384346").done();
    b.property("team_name", 0x37f2b1723c23d41eL).type(PrimitiveTypeId.STRING).origin("4031479720643384350").done();
    b.alias("badge");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCoach() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Coach", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c264298L);
    b.class_(false, false, false);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643543704");
    b.version(3);
    b.property("firstname", 0x37f2b1723c264299L).type(PrimitiveTypeId.STRING).origin("4031479720643543705").done();
    b.property("surname", 0x37f2b1723c26429bL).type(PrimitiveTypeId.STRING).origin("4031479720643543707").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Field", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c2e0dd5L);
    b.class_(false, false, false);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720644054485");
    b.version(3);
    b.property("field_size", 0x37f2b1723c226666L).type(MetaIdFactory.dataTypeId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22664dL)).origin("4031479720643290726").done();
    b.property("field_type", 0x37f2b1723c22a9b1L).type(MetaIdFactory.dataTypeId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22666fL)).origin("4031479720643307953").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLineup() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Lineup", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c31f5c8L);
    b.class_(false, false, true);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720644310472");
    b.version(3);
    b.alias("Lineup");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMatch() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Match", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c220732L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643266354");
    b.version(3);
    b.property("location", 0x37f2b1723c31f620L).type(PrimitiveTypeId.STRING).origin("4031479720644310560").done();
    b.property("date", 0x37f2b1723c31f62aL).type(PrimitiveTypeId.STRING).origin("4031479720644310570").done();
    b.property("home_team_goals", 0x37f2b1723c31f630L).type(PrimitiveTypeId.INTEGER).origin("4031479720644310576").done();
    b.property("away_team_goals", 0x37f2b1723c31f637L).type(PrimitiveTypeId.INTEGER).origin("4031479720644310583").done();
    b.property("home_formation", 0x37f2b1723c4a2bcdL).type(MetaIdFactory.dataTypeId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c4a2b8fL)).origin("4031479720645897165").done();
    b.property("away_formation", 0x37f2b1723c4a2bd3L).type(MetaIdFactory.dataTypeId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c4a2b8fL)).origin("4031479720645897171").done();
    b.aggregate("field", 0x37f2b1723c2e0df3L).target(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c2e0dd5L).optional(false).ordered(true).multiple(false).origin("4031479720644054515").done();
    b.aggregate("home", 0x37f2b1723c31f645L).target(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667bL).optional(false).ordered(true).multiple(false).origin("4031479720644310597").done();
    b.aggregate("away", 0x37f2b1723c3a3c4aL).target(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667bL).optional(false).ordered(true).multiple(false).origin("4031479720644852810").done();
    b.alias("Create Match Overview");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlayer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Player", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667aL);
    b.class_(false, false, false);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290746");
    b.version(3);
    b.property("firstname", 0x37f2b1723c228c03L).type(PrimitiveTypeId.STRING).origin("4031479720643300355").done();
    b.property("surname", 0x37f2b1723c226f86L).type(PrimitiveTypeId.STRING).origin("4031479720643293062").done();
    b.property("number", 0x37f2b1723c226f8aL).type(PrimitiveTypeId.INTEGER).origin("4031479720643293066").done();
    b.property("position", 0x37f2b1723c25456aL).type(MetaIdFactory.dataTypeId(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c23d431L)).origin("4031479720643478890").done();
    b.property("yellow_card", 0x37f2b1723c45cffbL).type(PrimitiveTypeId.BOOLEAN).origin("4031479720645611515").done();
    b.property("red_card", 0x37f2b1723c45d001L).type(PrimitiveTypeId.BOOLEAN).origin("4031479720645611521").done();
    b.alias("player");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTeam() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Football", "Team", 0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667bL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:773d5fe7-79b0-4318-a269-1850a325c198(Football.structure)/4031479720643290747");
    b.version(3);
    b.aggregate("coach", 0x37f2b1723c26429fL).target(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c264298L).optional(false).ordered(true).multiple(true).origin("4031479720643543711").done();
    b.aggregate("players", 0x37f2b1723c226f8eL).target(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c22667aL).optional(true).ordered(true).multiple(true).origin("4031479720643293070").done();
    b.alias("Set up Team");
    return b.create();
  }
}
