package Football.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Match_Constraints extends BaseConstraintsDescriptor {
  public Match_Constraints() {
    super(CONCEPTS.Match$3m);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Match$3m = MetaAdapterFactory.getConcept(0x578acf0eb7d44676L, 0x821617695aa51b90L, 0x37f2b1723c220732L, "Football.structure.Match");
  }
}
